let frases	= [
	"Procrastinar é acreditar no potencial do seu 'eu' do amanhã!",
	"Nada é tão horrível que não possa piorar muito!",
	"O não você já tem, agora falta buscar a humilhação",
	"Não deixe pra desistir amanhã o que você pode desistir hoje",
	"Não deixe pra amanhã o que pode ficar pra depois de amanhã",
	"Finalmente ela olhou pra você. E te achou feio.",
	"Sua cara metade virou gay!",
	"Ela não está offline. Você está bloqueado",
	"Quanto mais frases de superação você posta, mais a gente sabe que você não superou nada",
	"Nunca foi azar, sempre foi incompetência",
	"Pra ficar ruim tem que melhorar muito",
	"Dias ruins constroem dias piores",
	"De onde menos se espera é que não sai nada mesmo",
	"Parece que está ruim, mas vai piorar",
	"Tanto esforço pra porra nenhuma!",
	"Não deixe pra amanhã o que pode dar errado hoje",
	"Relaxa, nada vai dar certo",
	"A luta é grande mas a derrota é certa",
	"Nunca se esqueça que você é limitado",
	"Nada é em vão, tudo vem pra te decepcionar",
	"Nunca deixe ninguém dizer que você não consegue. Diga você mesmo: Eu não consigo!",
	"Esqueça os erros de ontem, comece a fazer os erros de hoje",
	"Fracasse enquanto eles dormem",
	"Se ainda não deu errado é porque ainda não acabou",
	"Os humilhados serão humilhados",
	"Tudo vai de mal a pior",
	"Acorde cedo para se atrasar com calma", 
	"Gratidão por mais um fracasso	", 
	"Sorria, o fracasso é inevitável	", 
	"Você ainda não chegou lá, mas olha o quanto você já se fudeu	", 
	"A cada novo passo, um novo passo pra trás	", 
	"Lute como um perdedor	", 
	"No inicio você acha que não vai conseguir, depois você tem certeza	", 
	"Até o cheque é especial e você não	", 
	"Nunca acredite em você	", 
	"Seu maior problema é você	", 
	"Todos os caminhos levam ao fracasso	", 
	"Sem luta não há derrota	", 
	"Criar metas é um caminho seguro para o fracasso	", 
	"Falhar não é uma escolha, é uma certeza	", 
	"O sofrimento de hoje é a derrota de amanhã	", 
	"Os planos para amanhã darão errado hoje	", 
	"Todo erro começa com a decisão de tentar	", 
	"Lute como nunca, fracasse como sempre	", 
	"Seja o problema das suas soluções	", 
	"Comemore as pequenas derrotas	", 
	"Muda o seu mindset para o fracasso	", 
	"O que tiver de ser seu nunca será	", 
	"A vida é um conto de falhas	", 
	"Hoje é um belo dia para fracassar	", 
	"Não desanime! Amanhã tem uma nova derrota	", 
	"Até os boletos vencem e você não	", 
	"Você não é incrível	", 
	"É só uma fase ruim, logo vai piorar!	", 
	"Não espere dar certo, faça dar errado	", 
	"Se esforce o máximo para estragar o pouco do que ainda resta	", 
	"Nunca é tarde demais para errar tudo de novo	", 
	"Relaxa, nada está sob controle	", 
	"Não pare até se humilhar	", 
	"Nunca subestime sua incapacidade	", 
	"Os últimos serão os últimos	", 
	"A prática leva a frustração	", 
	"Não tenha medo do fracasso. Tenha costume	", 
	"Você tem tudo pra dar errado	", 
	"Você não pode mudar seu passado. Mas pode estragar o seu futuro	", 
	"Persistir nunca, desistir sempre	", 
	"Nada como um dia pior que o outro	", 
	"Quanto maior a sua luta, maior a sua derrota"
];

module.exports = (msg)=>{
	msg.reply((frases[Math.floor(Math.random() * frases.length)] || frases[Math.floor(Math.random() * frases.length)]));
};
